sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LSE-319.pdf --upload --lsstdoc LSE-319.tex --env=travis --ltd-product LSE-319"
env:
  global:
    # LSST the Docs credentials
    - secure: "V/sQB1PlrK/JqDgnZBy9V/90ffKmJSvo2FiH4ayRMa75JIWiD1rAAchTSPsi7y2LWpRs3NvgKpEcekK01iKLSFXcFqGkTFhlK2bQG/6oCmwsq6OL2gANPyER9NDFqEwrruMcgDDPf3LivVCX/iy7cxC0+QwAq/qapuE1gddR+Onlq57bm7VAtI+Psx2ETzPVO1zlS6l4e03cyRFoXYfBKSy24TB0cxTHMVTTebNKXmb2f0dRV9tGtDPQsoVmhI4mVXVHtkZ5NnTYebv+X1+3i5XeAx5Xjr09JvvMuko5rj8pIueInT+qBQAIM6oWoT0KB0GZ5tehj4VwL1a0zvl9CNmgGcuRqQH4xdYmr3GuV770OoXz+7pHW/ZwEXSwUAfmAlKYoDnZ+EmD4m/RcVTxyfqhFrimFw3k64aEEa7zivIK1OKFOJVRNmuRVKsW8fpJXnhEp2Rb5v5KM/SgtRQ7As9OpULsd1duZAAgFR++F00oqiWwBKKd2QrniWL+Q34/guCyNINY3jI/DOVito5b2tWuZphSUkFoRNqsMDV/3cY5GnMRBqEhlZLoZTLm/tO16s+mmeEzQ34OY1861bMct0FzQXtcbcL2SDkDKHJYtVyKZmvC8dzMU0hfUJigUxcarhxbREUIGlYGoNjgI4DanOn/VwsdkIbsAIhnC1iksV0="
    - secure: "hlQQcK1eH5KtrjOtJODjKUIaqdbca/qMDQQG7Ox417t0eojrmcH+eKTz/ZNGqJJNUtTAJ3xYFCO55+VKU9EPa6Qr//B+vjP3l9UplgWZBNFnScQ72YXgLvuTKzjHZCnzZdr8L8cBPlfi3GltZI+BxETvgDfs0d2C/yvXObPx1XTVg9PDoYEXicfsTHPpPcHw4slqUiwsQ1bK4lJCNvDy/+E5pTA0+mT+85jtStLkre4iUtXTtlNZSo6MAS1AncbJyzgl6TTHq0RoE0JAFxKxUlQ8gpn+5/SutHokDXgtF5Ewr7Csy9rsf29HO5chiAt0qcpXBTp0GmJGPVUUqzhYVxJaBZFPWlei1zcsRSwrFDcyP5JNVgj9EiAaf8HK/7X31n8xPGhD7iIUAXm5+D3VlMGHuSKDYL7v/lDwT1AzFQQg6JcG1F95NW00ZrnjxvpTt1ig+aCGTTqM0l9iZ2aij23WW54+Qfhh0kUgJXu37Joxbd57CLoJcQ8vyfBS6TCLIrdyIb8FDxgpxjVLsIYlyFzJYOCoyful3nuNkVCRnnQZ6MRoZ36Ya/+0AIqyJNv/xMNtDzwKeahDdthtxkx2wZDiJnY6NKv/FlySW2BStvkheqrHLIqC7Qf3opx67XjWT2loLr2oRQ1oIuvGe4EXqGG67tppeiIJQt4EON/nGxY="
